compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.0.2.cjs

# TODO: remove once taquito releases a new version
npmRegistryServer: https://npm.preview.tezostaquito.io
