compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

# TODO: remove once taquito releases a new version
npmRegistryServer: "https://npm.preview.tezostaquito.io"

yarnPath: .yarn/releases/yarn-4.1.0.cjs
