version: "3.8"

services:
  db:
    container_name: "tzkt-db-${CUCUMBER_WORKER_ID:-0}"
    restart: always
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-tzkt}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-qwerty}
      POSTGRES_DB: ${POSTGRES_DB:-tzkt_db}

  flextesa:
    container_name: "tezos-node-${CUCUMBER_WORKER_ID:-0}"
    restart: always
    image: ${FLEXTESA_IMAGE:-serjonya/flextesa:latest}
    command: nairobibox start
    healthcheck:
      test: octez-client get balance for alice
      interval: 1s
      timeout: 5s
      retries: 100
      start_period: 5s
    environment:
      block_time: 1

  proxy:
    depends_on:
      - flextesa
    container_name: "tezos-node-proxy-${CUCUMBER_WORKER_ID:-0}"
    restart: always
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 2000${CUCUMBER_WORKER_ID:-0}:80

  sync:
    container_name: "tzkt-sync-${CUCUMBER_WORKER_ID:-0}"
    restart: always
    image: ${TZKT_SYNC_IMAGE:-serjonya/tzkt-sync:1.13.3}
    environment:
      ConnectionStrings__DefaultConnection: host=db;port=5432;database=${POSTGRES_DB:-tzkt_db};username=${POSTGRES_USER:-tzkt};password=${POSTGRES_PASSWORD:-qwerty};command timeout=${COMMAND_TIMEOUT:-600};
      Kestrel__Endpoints__Http__Url: http://0.0.0.0:5001
      TezosNode__Endpoint: http://flextesa:20000
      Home__Enabled: "true"
      HealthChecks__Enabled: "true"
    depends_on:
      - db
      - flextesa

  api:
    container_name: "tzkt-api-${CUCUMBER_WORKER_ID:-0}"
    restart: always
    image: ${TZKT_API_IMAGE:-serjonya/tzkt-api:1.13.3}
    depends_on:
      - sync
    environment:
      ConnectionStrings__DefaultConnection: host=db;port=5432;database=${POSTGRES_DB:-tzkt_db};username=${POSTGRES_USER:-tzkt};password=${POSTGRES_PASSWORD:-qwerty};command timeout=${COMMAND_TIMEOUT:-600};
      Kestrel__Endpoints__Http__Url: http://0.0.0.0:5000
      Home__Enabled: "true"
      HealthChecks__Enabled: "true"
      ResponseCache__CacheSize: 0
    healthcheck:
      test: curl -f http://localhost:5000/v1/accounts
      interval: 1s
      timeout: 1s
      retries: 100
      start_period: 10s
    ports:
      - 500${CUCUMBER_WORKER_ID:-0}:5000

networks:
  default:
    name: "tzkt-network-${CUCUMBER_WORKER_ID:-0}"
