# IF YOU UPDATE THIS FILE
# ALSO UPDATE docker-compose.yaml
version: "3.8"

services:
  db:
    container_name: tzkt-db
    restart: always
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-tzkt}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-qwerty}
      POSTGRES_DB: ${POSTGRES_DB:-tzkt_db}
    ports:
      - 5432:5432

  flextesa:
    container_name: tezos-node
    restart: always
    image: oxheadalpha/flextesa:latest
    command: nairobibox start
    healthcheck:
      test: octez-client get balance for alice
      interval: 1s
      timeout: 5s
      retries: 100
      start_period: 5s
    environment:
      block_time: 1

  proxy:
    depends_on:
      - flextesa
    container_name: tezos-node-proxy
    restart: always
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 20001:80

  sync:
    container_name: tzkt-sync
    restart: always
    image: serjonya/tzkt-sync:1.12.4-linux
    environment:
      ConnectionStrings__DefaultConnection: host=db;port=5432;database=${POSTGRES_DB:-tzkt_db};username=${POSTGRES_USER:-tzkt};password=${POSTGRES_PASSWORD:-qwerty};command timeout=${COMMAND_TIMEOUT:-600};
      Kestrel__Endpoints__Http__Url: http://0.0.0.0:5001
      TezosNode__Endpoint: ${NODE_RPC:-http://flextesa:20000/}
      Home__Enabled: "true"
      HealthChecks__Enabled: "true"
    depends_on:
      - db
      - flextesa

  api:
    container_name: tzkt-api
    restart: always
    image: serjonya/tzkt-api:1.12.4-linux
    depends_on:
      - sync
    environment:
      ConnectionStrings__DefaultConnection: host=db;port=5432;database=${POSTGRES_DB:-tzkt_db};username=${POSTGRES_USER:-tzkt};password=${POSTGRES_PASSWORD:-qwerty};command timeout=${COMMAND_TIMEOUT:-600};
      Kestrel__Endpoints__Http__Url: http://0.0.0.0:5000
      Home__Enabled: "true"
      HealthChecks__Enabled: "true"
      ResponseCache__CacheSize: 0
    healthcheck:
      test: curl -f http://localhost:5000/v1/accounts
      interval: 1s
      timeout: 1s
      retries: 100
      start_period: 10s
    ports:
      - 5000:5000

networks:
  default:
    name: tzkt
