name: E2E Tests

on: push

jobs:
  test:
    permissions: write-all
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup yarn 3.x
        run: |
          corepack enable
          yarn set version 3.5.0

      - uses: actions/setup-node@v4
        with:
          node-version: 18.15.x
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Start dev server
        run: yarn start &

      - name: Pull docker images
        run: docker compose -f docker-compose.ci.yaml pull --quiet

      - name: Install Playwright Browsers
        run: yarn playwright install chromium --with-deps

      - name: Wait until the server is ready
        run: yarn exec wait-on http-get://127.0.0.1:3000

      - name: Run Playwright tests
        run: yarn playwright test

      - name: Run cucumber tests
        run: yarn test:e2e

      - name: Cucumber Report to Annotations
        uses: deblockt/cucumber-report-annotations-action@v1.12
        if: always()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "test-results/cucumber-report.json"

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 10
