name: Test

on: push

permissions:
  pull-requests: write
  checks: write
  contents: write

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max_old_space_size=4096"
    steps:
      - uses: actions/checkout@v4

      - uses: jwalton/gh-find-current-pr@v1
        id: findPr

      - name: Setup yarn
        run: |
          corepack enable
          yarn set version stable

      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.x
          cache: "yarn"

      - name: Install packages
        run: yarn install --immutable

      - name: Check format
        run: yarn format:ci

      - name: Run linter
        run: yarn lint:ci

      - name: Run tests
        uses: ArtiomTr/jest-coverage-report-action@v2.2.6
        with:
          skip-step: install
          test-script: yarn test
          annotations: coverage
          base-coverage-file: report.json
          prnumber: ${{ steps.findPr.outputs.number }}

      # Uncomment when taquito releases a new version
      # - name: Audit dependencies
      #   run: yarn npm audit
